"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$hostname\
$directory\
$git_branch\
$git_status\
$line_break
$character\
"""

right_format = """
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_fg1 = '#faeba7'

[hostname]
ssh_only = false
format = '[ cherryüçí ](bold white)'

[directory]
style = "fg:color_fg0"
format = "[at $path ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[git_branch]
symbol = "Ôêò"
format = '[on $symbol $branch ](fg:color_fg1)'

[git_status]
format = '[($all_status$ahead_behind )](fg:color_fg1)'

[docker_context]
symbol = "Ôåà"
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:blue)'
error_symbol = '[!](bold fg:color_red)'
vimcmd_symbol = '[Ôê¥](bold fg:color_green)'
vimcmd_replace_one_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_replace_symbol = '[Ôê¥](bold fg:color_purple)'
vimcmd_visual_symbol = '[Ôê¥](bold fg:color_yellow)'
